page:
  styles:
  media:
  background:
    top: 1.75rem
    desktopBackground: "/static/8-bb59fe4c695f616c31441294275e2a79.svg"
    mobileBackground: "/static/6-0f2ac2394e64c8eef84ee5bd259ab4c2.jpg"
    fallbackBackground: "/static/8-bb59fe4c695f616c31441294275e2a79.svg"
  blocks:
  - type: header2
    styles:
      backgroundColor: "#e8d9cb"
      border: 0.15rem solid
      borderRadius: 3rem 3rem 0 0
      fontSize: clamp(1rem, 2vw, 2.4rem)
      lineHeight: 1.2
      transform: translate(-50%, -50%) scale(0.9)
      width:
      height:
      right:
      left: 50%
      top: 19%
      bottom:
      paddingInline: 2em
      paddingBlock: 1.5em
      textContent: "KONTAKT <br/> Z ORGANIZATORAMI"
    media:
  - type: organizer
    styles:
      backgroundColor: "#e8d9cb"
      border: 0.1rem solid
      borderRadius: 2rem
      color: "#d2764a"
      fontSize: 0.9vw
      width: 17%
      height: 10%
      right:
      left: 9.9%
      top: 85%
      bottom: 8%
      organizerName: 'MIKOŁAJ ŻUCHOWSKI <br />{" "}'
      nameFontSize: 120%
      nameFontWeight: 600
      textContent: "KOODRYNATOR DS. LOGISTYKI <br />
          508 411 959 <br />
          MIKOLAJ.ZUCHOWSKI@BEST.KRAKOW.PL <br />"
    media:
  - type: organizer
    styles:
      backgroundColor: "#e8d9cb"
      border: 0.1rem solid
      borderRadius: 2rem
      color: "#d2764a"
      fontSize: 0.9vw
      width: 17%
      height: 10%
      right:
      left: 41.6%
      top: 85%
      bottom: 8%
      organizerName: 'PAULINA SKRZYPCZAK <br /> {" "}'
      nameFontSize: 120%
      nameFontWeight: 600
      textContent: "GŁÓWNY KOORDYNATOR <br />
          516 321 234 <br />
          PAULINA.SKRZYPCZAK@BEST.KRAKOW.PL <br />"
    media:
  - type: organizer
    styles:
      backgroundColor: "#e8d9cb"
      border: 0.1rem solid
      borderRadius: 2rem
      color: "#d2764a"
      fontSize: 0.9vw
      width: 17%
      height: 10%
      right:
      left: 72.9%
      top: 85%
      bottom: 8%
      organizerName: 'MATEUSZ WIRKIJOWSKI <br />{" "}'
      nameFontSize: 120%
      nameFontWeight: 600
      textContent: "KOODRYNATOR DS. KONTAKTU Z FIRMAMI <br />
          530 397 519 <br />
          MATEUSZ.WIRKIJOWSKI@BEST.KRAKOW.PL <br />"
    media: