page:
  styles:
    top: 2em
  background:
  media:
  blocks:
    - type: text
      styles:
        color: "yellow"
        content: "I'm Text One!"
      media:
    - type: text
      styles:
        color: "blue"
        content: "I'm Text Two!"
      media:
    - type: composite
      styles:
      media:
      blocks:
        - type: text
          styles:
            color: "#d2764a"
            content: "Hello World!"
          media:
        - type: text
          styles:
            color: "#d2764a"
            content: "Goodbye World..."
          media: