page:
  styles:
    position: relative
    display: grid
    top: 1.75rem
  background:
  media:
  blocks:
  # background no. 1
  - type: image
    styles:
      width: 100%
      height: 100%
      right:
      left:
      top:
      padding:
      transform:
      position: relative
      src: "/static/4-c6113b019a83f17193bc0e9d71d014f4.svg"
    media:
  # background no. 2
  - type: image
    styles:
      width: 100%
      height: 100%
      right:
      left:
      top:
      padding:
      transform:
      position: relative
      src: "/static/5-b8745e4832fdf012b7ce706360f91f92.svg"      
    media:
  # partners
  - type: image
    styles:
      width: 100%
      height: 100%
      right:
      left:
      top:
      padding:
      transform:
      position: relative
      src: "/static/6-f09b81d7c73981fcc9bd9a4e0eefc571.svg"
    media:
  # patrons
  - type: image
    styles:
      width: 100%
      height: 100%
      right:
      left:
      top:
      padding:
      transform:
      position: relative
      src: "/static/7-b4c57100f42d5d2532040a8264b8e0c5.svg"
    media:
    # Tytul: Sponsor Glowny
  - type: title
    styles:
      width: 18%
      height: 3.2%
      right:
      left: 43%
      top: 5.7%
      fontSize: 2.4vw
      backgroundColor: "#ead8ce"
      color: "#d2764a"
      textContent: "SPONSOR GŁÓWNY"
    media:
    # Tytul: Sponsorzy
  - type: title
    styles:
      width: 18%
      height: 3.2%
      right:
      left: 41%
      top: 28.4%
      fontSize: 2.4vw
      backgroundColor: "#ead8ce"
      color: "#d2764a"
      textContent: "SPONSORZY"
    media:
    # Tytul: Partner Strefy Studenta
  - type: title
    styles:
      width: 18%
      height: 4%
      right:
      left: 9.7%
      top: 56%
      fontSize: 2.7vw
      backgroundColor: "#ead8ce"
      color: "#d2764a"
      textContent: "PARTNER <br /> STREFY <br /> STUDENTA"
    media:
    # Tytul: Partner Merytoryczny
  - type: title
    styles:
      width: 18%
      height: 4%
      right:
      left: 41%
      top: 56%
      fontSize: 2.7vw
      backgroundColor: "#ead8ce"
      color: "#d2764a"
      textContent: "PARTNER <br /> MERYTORYCZNY"
    media:
    # Tytul: Partner Techniczny
  - type: title
    styles:
      width: 18%
      height: 4%
      right:
      left: 72%
      top: 56%
      fontSize: 2.7vw
      backgroundColor: "#ead8ce"
      color: "#d2764a"
      textContent: "PARTNER <br /> TECHNICZNY"
    media:
    # Tytul: Partnerzy Medialni
  - type: title
    styles:
      width: 18%
      height: 3.2%
      right:
      left: 41%
      top: 78.2%
      fontSize: 2.4vw
      backgroundColor: "#ead8ce"
      color: "#d2764a"
      textContent: "PARTNERZY <br /> MEDIALNI"
    media:
  # sponsor glowny - Sabre
  - type: partner
    styles:
      width: 20%
      right: 38%
      left:
      top: 16%
      link: "https://www.sabre.com/locations/poland/"
      src: "/static/00_SG_Sabre-f55087bee8afedc3cbcd7418d677a8e6.png"
      alt: "Sabre"
      position: absolute
    media:
      width: 38%
      right: 32%
      left:
      top: 3.5%
 # sponsor - Woodward
  - type: partner
    styles:
      width: 20%
      right: 38%
      left: 8.8%
      top: 36.6%
      link: "https://www.woodward.com/"
      src: "/static/01_S_Woodward-0c8e9bb3dc96045c806977324ceeaaf3.png"
      alt: "Woodward"
      position: absolute
    media:
      width: 30%
      right:
      left: 7%
      top: 32%
 # sponsor - Pega
  - type: partner
    styles:
      width: 9%
      right:
      left: 45.6%
      top: 36%
      link: "https://www.pega.com/"
      src: "/static/02_S_Pega-8b846115dc448c260d76f83142668cb3.png"
      alt: "Pega"
      position: absolute
    media:
      width: 17%
      right:
      left: 69%
      top: 31%
 # sponsor - Mars
  - type: partner
    styles:
      width: 11%
      right: 13%
      left:
      top: 36.6%
      link: "https://www.mars.com/"
      src: "/static/03_S_Mars-c79a4842bca018ea364eee5b17809037.png"
      alt: "Mars"
      position: absolute
    media:
      width: 17%
      right: 10.5%
      left:
      top: 39.4%
 # sponsor - aptiv
  - type: partner
    styles:
      width: 16%
      right:
      left: 10.5%
      top: 44%
      link: "https://www.aptiv.com/"
      src: "/static/3-595de51e8d57d44ec2ed50be019c7c22.png"
      alt: "aptiv"
      position: absolute
    media:
      width: 27%
      right:
      left: 8.4%
      top: 48.4%
 # sponsor - Motorola
  - type: partner
    styles:
      width: 9%
      right:
      left: 45.8%
      top: 43%
      link: "https://www.motorolasolutions.com/en_us/home.html"
      src: "/static/05_S_Motorola-f6e1e5251a69a3e9fe51224d6a79744d.png"
      alt: "Motorola"
      position: absolute
    media:
      width: 16%
      right:
      left: 14.5%
      top: 38.5%
 # sponsor - Autodesk
  - type: partner
    styles:
      width: 18.8%
      right: 9.4%
      left:
      top: 44.1%
      link: "https://www.autodesk.com/"
      src: "/static/06_S_Autodesk-d97eed74844c737fb8352773110a145c.png"
      alt: "Autodesk"
      position: absolute
    media:
      width: 32%
      right: 6.2%
      left:
      top: 48.5%
 # PSS - GE Healthcare
  - type: partner
    styles:
      width: 15%
      right: 74%
      left:
      top: 65.4%
      link: "https://www.ge.com/"
      src: "/static/07_PSS_GE_Healthcare-c5a2ab6c49564ad25746ded871fb876d.png"
      alt: "GE"
      position: absolute
    media:
      width: 24%
      right: 71.5%
      left:
      top: 69.5%
 # PMT - Adecco
  - type: partner
    styles:
      width: 12%
      right: 43.7%
      left:
      top: 65.3%
      link: "https://www.adecco.pl/"
      src: "/static/08_PMT_Adecco-67f9b229b807ea4c8010d63dbe6bae37.png"
      alt: "Adecco"
      position: absolute
    media:
      width: 22%
      right: 38.8%
      left:
      top: 65.6%
 # PT - Fujijama
  - type: partner
    styles:
      width: 12%
      right: 12.5%
      left:
      top: 65.5%
      link: "https://www.fujijama.pl/"
      src: "/static/15_PT_Fujijama-01df48daafadf4924e22f81621255bcc.svg"
      alt: "Fujijama"
      position: absolute
    media:
      width: 19%
      right: 7.1%
      left:
      top: 66%
 # PMD - Eska
  - type: partner
    styles:
      width: 12%
      right:
      left: 13%
      top: 86.2%
      link: "https://www.eska.pl/"
      src: "/static/09_PMD_Eska-a9ca97313f2d6be0dcaec96462779031.png"
      alt: "Eska"
      position: absolute
    media:
      width: 28%
      right:
      left: 8.8%
      top: 80.5%
 # PMD - Podaj Dalej
  - type: partner
    styles:
      width: 10%
      right: 45.2%
      left:
      top: 86.2%
      link: "http://www.podajdalej.info.pl/"
      src: "/static/10_PMD_Podaj_Dalej-6acb54c0258c16d46e774fbe25d6ae64.png"
      alt: "Podaj Dalej"
      position: absolute
    media:
      width: 28%
      right: 12%
      left:
      top: 96.2%
 # PMD - Dla Studenta
  - type: partner
    styles:
      width: 11%
      right: 13%
      left:
      top: 86.4%
      link: "https://www.dlastudenta.pl/"
      src: "/static/11_PMD_Dla_Studenta-bdfc53e6c6f8aad93fba88b210d62993.png"
      alt: "Dla Studenta"
      position: absolute
    media:
      width: 22%
      right: 10.7%
      left:
      top: 80.8%
 # PMD - Eurostudent
  - type: partner
    styles:
      width: 14%
      right:
      left: 11.7%
      top: 93.2%
      link: "https://eurostudent.pl/"
      src: "/static/12_PMD_Eurostudent-a7592c006038c30c87605d9ad2b992e4.png"
      alt: "Eurostudent"
      position: absolute
    media:
      width: 30%
      right:
      left: 7.5%
      top: 88.5%
 # PMD - KMS
  - type: partner
    styles:
      width: 13%
      right: 44%
      left:
      top: 93.4%
      link: "https://kms.org.pl/"
      src: "/static/13_PMD_KMS-5db955400e5ee60c36b192b17f5f9cb6.png"
      alt: "KMS"
      position: absolute
    media:
      width: 25%
      right: 66%
      left:
      top: 96.3%
 # PMD - FXMAG
  - type: partner
    styles:
      width: 5%
      right: 15.6%
      left:
      top: 93.4%
      link: "https://fxmag.pl/"
      src: "/static/3-595de51e8d57d44ec2ed50be019c7c22.png"
      alt: "FXMAG"
      position: absolute
    media:
      width: 11%
      right: 16%
      left:
      top: 88.6%