page:
  styles:
    width: 100%
    height: 100vh
    background: "#efd7bf url(${tlo_pc_1})"
    background-size: cover
    background-position: bottom
    position: relative
  media:
    height: "calc(100vh - 6vh - 1em)"
  background:
  blocks:
    - type: composite
      styles:
        position: absolute
        top: 32%
        left: 50%
        transform: translate(-50%, -50%)
        width: clamp(12rem, 80vw, 36rem)
        text-align: center
      media:
        width: clamp(12rem, 50vw, 36rem)
        transform: none
        top: 10%
        left: 7%
        text-align: left
      blocks:
        - type: image
          width: 100%
          display: block
          margin-block: 1.6rem
          margin-inline: auto
          src: "ITP_logo"
          media:
            width: 98%
            margin-inline: 0
        - type: header2
          font-size: "clamp(0.8rem, 5vw, 2.5rem)"
          line-height: 1.15
          content: "8 marca 2023"
          media:
            font-size: "clamp(1.7rem, 2.5vw, 2.5rem)"
            line-height: 1.2
        - type: header2
          font-size: "clamp(0.8rem, 5vw, 2.5rem)"
          line-height: 1.15
          content: "10:00-16:00"
          media:
            font-size: "clamp(1.7rem, 2.5vw, 2.5rem)"
            line-height: 1.2
        - type: header2
          font-size: "clamp(0.8rem, 4.6vw, 2rem)"
          line-height: 1.15
          content: "stadion miejski im. Henryka Reymana"
          media:
            font-size: "clamp(1.5rem, 2.2vw, 2.2rem)"
            line-height: 1.2
      - type: image
        position: absolute
        width: "clamp(8rem, 24vw, 20rem)"
        right: 0
        margin-top: 4vh
        margin-right: 6vw
        user-select: none
        src: "BEST_logo"
        media:
          margin-top: 2vh
          margin-right: 4vw